-- 1. Criar tabela de afiliados
CREATE TABLE IF NOT EXISTS afiliados (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	telefone VARCHAR(20) DEFAULT NULL,
	senha VARCHAR(255) NOT NULL,
	code VARCHAR(32) NOT NULL UNIQUE,
	ultimo_login DATETIME DEFAULT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	atualizado_em TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	INDEX idx_telefone (telefone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Criar tabela de participantes
CREATE TABLE IF NOT EXISTS participantes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	telefone VARCHAR(20) NOT NULL,
    instagram VARCHAR(31) NOT NULL UNIQUE,
	e1 TINYINT(1) DEFAULT 0,
	e2 TINYINT(1) DEFAULT 0,
	e3 TINYINT(1) DEFAULT 0,
	e4 TINYINT(1) DEFAULT 0,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	atualizado_em TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	parametro_unico VARCHAR(255) DEFAULT NULL,
	INDEX idx_telefone (telefone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;